CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ldap_login VARCHAR2(100) NOT NULL UNIQUE,
    first_name VARCHAR2(100),
    last_name VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO employees (ldap_login, first_name, last_name)
VALUES ('petro.doroshenko', 'Petro', 'Doroshenko');
INSERT INTO employees (ldap_login, first_name, last_name)
VALUES ('anna.lysenko', 'Anna', 'Lysenko');
INSERT INTO employees (ldap_login, first_name, last_name)
VALUES ('bohdan.khmelnytskyi', 'Bohdan', 'Khmelnytskyi');
COMMIT;